# global variables
GV:
  RepoBase: "https://github.com/semichkin-gopkg"
  LoadingFolder: "services"

Expressions:
  - export FROM_EXPRESSIONS := $(shell echo "from_expressions")

EnvFiles:
  - import.env

GlobalRules:
  Start: "cd docker && docker-compose up -d --build"
  Stop: "cd docker && docker-compose down"
  Restart: "make Stop && make Start"
  EnvFilesTest: "@echo ${FROM_IMPORT_ENV}"
  ExpressionsTest: "@echo ${FROM_EXPRESSIONS}"

MainRules:
  - "Load"
  - "Actualize"

DefaultServiceRules:
  Load: >
    make _clone \
    repo="{{GV.RepoBase}}/{{V.Path}}.git" \
    to="{{GV.LoadingFolder}}/{{V.Path}}" &&
    cd {{GV.LoadingFolder}}/{{V.Path}} &&
    (make Load || true)
  Actualize: >
    make {{V.ServiceName}}_Load &&
    cd {{GV.LoadingFolder}}/{{V.Path}} &&
    git pull origin $(git branch --show-current) &&
    (make Actualize || true)

Services:
  - Name: Env
    Groups: ["_all"] # group _all tells that service rules should be included to all other groups
    # service variables
    V:
      Path: "env"
  - Name: Configurator
    Groups: ["Namespace1", "Namespace2"]
    V:
      Path: "configurator"
  - Name: Promise
    Groups: ["Namespace1"]
    V:
      Path: "promise"
    Rules:
      Load: "git clone {some_2}"
      Unique: "echo 'test'"
  # etc...
