# global variables
GV:
  RepoBase: "https://github.com/semichkin-gopkg"
  LoadingFolder: "services"

GlobalRules:
  CloneIfNotExists: >
    [ -d "${to}" ] || git clone ${repo} ${to}

EnabledRules:
  - "Load"
  - "Actualize"

Services:
  Configurator:
    # service variables
    V:
      Path: "configurator"
  Promise:
    V:
      Path: "promise"
  # etc...

DefaultServiceRules:
  Load: >
    make CloneIfNotExists \

    repo="{{GV.RepoBase}}/{{V.Path}}.git" \

    to="{{GV.LoadingFolder}}/{{V.Path}}"

  Actualize: >
    make {{V.ServiceName}}_Load &&
    cd {{GV.LoadingFolder}}/{{V.Path}} &&
    git pull origin $(git branch --show-current)